Support No Type
MeltanoLabs/target-postgres pull request #183
Opened 2023-08-24 15:18 UTC by andyoneal

Uses string by default when a property in the schema does not include any type info.

fixes #168

2023-08-25 18:06 UTC, edgarrmondragon requested changes
Let's check how lists and dicts are serialized

2023-08-25 18:06 UTC, edgarrmondragon commented on target_postgres/tests/data_files/test_no_type.singer
> +{"type": "RECORD", "stream": "test_no_type", "record": {"Id": "0122P000001SXX0YXX", "IsDeleted": false, "ParentId": "a301O000000T601QAB", "CreatedById": "0056O00000XAxPxxLAX", "CreatedDate": "2023-08
I think it's worth adding an `object` test case here

```suggestion
{"type": "RECORD", "stream": "test_no_type", "record": {"Id": "0122P000001SXX0YXX", "IsDeleted": false, "ParentId": "a301O000000T601QAB", "CreatedById": "0056O00000XAxPxxLAX", "CreatedDate": "2023-08-23T14:00:56.000000Z", "Field": "Is_Bool__c", "DataType": "Boolean", "OldValue": false, "NewValue": true}, "version": 1692831045028, "time_extracted": "2023-08-23T22:50:45.047299Z"}
{"type": "RECORD", "stream": "test_no_type", "record": {"Id": "0122P000001SXX0YXY", "IsDeleted": false, "ParentId": "a301O000000T601QAB", "CreatedById": "0056O00000XAxPxxLAX", "CreatedDate": "2023-08-23T14:00:56.000000Z", "Field": "Is_Bool__c", "DataType": "Object", "OldValue": {"x": 1}, "NewValue": {"x": 2}}, "version": 1692831045028, "time_extracted": "2023-08-23T22:50:45.047299Z"
```

2023-08-25 18:53 UTC, andyoneal commented
Good call. Lists seem to work ok, but the object test hit this error `sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'`

2023-08-25 19:14 UTC, edgarrmondragon commented
> Good call. Lists seem to work ok, but the object test hit this error `sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'`

Yeah, I think for that to work we need to make column be of type `jsonb`. @visch any suggestions on what schema type will allow us to do that?

2023-08-25 19:52 UTC, visch commented
> > Good call. Lists seem to work ok, but the object test hit this error `sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'`
> 
> Yeah, I think for that to work we need to make column be of type `jsonb`. @visch any suggestions on what schema type will allow us to do that?

We could just make the schema be an `object` but we'll have the reverse problem for strings, etc.  We need to convert the data to a string regardless of it's type (or to a jsonb object, but String probably makes the most sense here)

I see two options to move forward here (probably more are available)
1.  Add a transform function https://github.com/MeltanoLabs/target-postgres/blob/main/target_postgres/sinks.py#L149-L150 and in the appendOnly section. Detect that this field needs to be checked by adding some metadata to the jsonschema here https://github.com/MeltanoLabs/target-postgres/pull/183/files#diff-d9dd2207eaf6595663ebc6779561ea07947567ea8ecd47c504915df8f078154eR244

2. Use a custom SQLAlchemy type like this https://stackoverflow.com/questions/28143557/sqlalchemy-convert-column-value-back-and-forth-between-internal-and-database-fo for our field and transform the data there. 

Something like
```python
from sqlalchemy import TypeDecorator, String
import json

class JSONEncodedDict(TypeDecorator):
    impl = String

    def process_bind_param(self, value, dialect):
        if value is not None and isinstance(value, dict):
            value = json.dumps(value)
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            value = json.loads(value)
        return value

class YourModel(Base):
    # ...
    your_column = Column(JSONEncodedDict())
 ```

2023-08-25 19:57 UTC, visch requested changes
Object/Lists! :D Thanks for the PR

2023-08-25 22:21 UTC, andyoneal commented
@visch got it to _technically_ work before I saw your suggestion here. the way I did it is hideous, so I was glad to see ideas for something more sensible. I'll likely redo this.

2023-08-25 22:48 UTC, visch commented
Nice @andyoneal , there is something to be said about converting the data types to work if the schema thinks the data should be a string generally. 

@andyoneal I'm in the phone so it's hard for me to tell right this second but do we also have lists handled?

2023-08-25 23:10 UTC, andyoneal commented
@visch yes, lists work too. although I am treating them the same as objects and deserializing them as json, so you end up with square brackets in the string instead of curly brackets. That's a little harder to cast from string to array in postgres.

another possibility is the way Stitch does it with their closed source target for Postgres. It seems like they're guessing the type for each record and splitting the column into correctly typed. So instead of a single string column, I've seen up to five typed variants in my data:
* ColumnName__st: text
* ColumnName__do: double precision
* ColumnName__de: numeric
* ColumnName__bo: boolean
* ColumnName__bi: bigint

We could extend that to include objects and arrays, but that could get out of hand quickly (especially with flattening turned on!) and is probably more complexity than this kind of edge case is worth.

What do you think? @visch @edgarrmondragon

2023-08-28 20:12 UTC, andyoneal commented
Went with the sql alchemy custom type approach

2023-08-28 21:03 UTC, visch requested changes
Looks really good, slight tweak!

2023-08-28 21:03 UTC, visch commented on target_postgres/connector.py
> +            json_type_array.append({"type": "string", "format": "no-type"})
```suggestion
            return NOTYPE()
```

2023-08-28 21:03 UTC, visch commented on target_postgres/connector.py
> +            return NOTYPE()
```suggestion
```

2023-08-28 22:25 UTC, andyoneal commented
that's way simpler. thanks.

2023-08-28 22:37 UTC, edgarrmondragon approved these changes

2023-08-28 22:37 UTC, edgarrmondragon commented
This LGTM. Thanks @andyoneal!

2023-08-28 23:08 UTC, visch approved these changes

2023-08-28 23:08 UTC, merged